name: 'Generate deployment package'
description: 'Generate deployment pacage'
inputs:      
  BRANCH_NAME:
    required: true
    type: string
  BASE_BRANCH_NAME:
    required: true
    type: string
  DEPLOYMENT_SCOPE:
    description: Deployment scope, expected values FULL | DELTA
    required: false
    default: DELTA
    type: string
  SGD_PACKAGE_DIR:
    description: SFDX git delta generated package directory
    required: false
    default: package
    type: string

runs:
  using: "composite"
  steps:
    - name: ⚙️ Checkout base branch
      if: ${{ inputs.DEPLOYMENT_SCOPE == 'DELTA' && inputs.DEPLOYMENT_MODE != 'QUICK' }}
      uses: actions/checkout@v6
      with:
        ref: ${{ inputs.BASE_BRANCH_NAME }}

    - name: ⚙️ Get base branch SHA
      if: inputs.DEPLOYMENT_SCOPE == 'DELTA'
      id: baseBranch
      shell: bash
      run: |
        echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
  
    - name: ⚙️ Checkout specified branch
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        ref: ${{ inputs.BRANCH_NAME }}

    - name: 🔍 Geneate Delta Package
      if: inputs.DEPLOYMENT_SCOPE == 'DELTA'
      shell: bash
      run: |
        # Create the output directory before running the SGD command
        mkdir "${{ inputs.SGD_PACKAGE_DIR }}"

        sf sgd source delta --from ${{ steps.baseBranch.outputs.sha }} --to ${{ inputs.BRANCH_NAME }} --output-dir "${{ inputs.SGD_PACKAGE_DIR }}"

    - name: 📋 Print Formatted Deployment List
      if: inputs.DEPLOYMENT_SCOPE == 'DELTA'
      shell: bash
      run: |
        echo "--- START METADATA TO BE DEPLOYED ---"
        
        # Use grep to find lines containing members and name tags.
        # Then, use awk to process them in sequence and format the output.
        cat ${{ inputs.SGD_PACKAGE_DIR }}/package/package.xml | \
          grep -E 'members|name' | \
          awk '
            /<members>/ {
              # 1. Extract and store the Member Name (remove tags)
              MEMBER = $0;
              gsub(/<(\/?members)>/, "", MEMBER);
            }
            /<name>/ {
              # 2. Extract and store the Metadata Type Name (remove tags)
              TYPE = $0;
              gsub(/<(\/?name)>/, "", TYPE);
              
              # 3. Print the stored pair in the desired format
              printf "%s : %s\n", TYPE, MEMBER;
            }'
        echo "--- END METADATA TO BE DEPLOYED ---"

    - name: 🔍 Geneate full Package
      if: inputs.DEPLOYMENT_SCOPE == 'FULL'
      shell: bash
      run: |
        # Create the output directory before running the SGD command
        mkdir "${{ inputs.SGD_PACKAGE_DIR }}"

        # 4b825dc642cb6eb9a060e54bf8d69288fbee4904 is Empty Tree SHA
        sf sgd source delta --from 4b825dc642cb6eb9a060e54bf8d69288fbee4904 --to ${{ inputs.BRANCH_NAME }} --output-dir "${{ inputs.SGD_PACKAGE_DIR }}"
